### PR TITLE
Raise an error if instance_type is not provided in resource_pool.

### LINKED ISSUE #123: cpi should raise an error if instance_type is not set for create_vm call
right now it doesnt so azure gets confused and shows following error message.

```
/var/vcap/packages/bosh_azure_cpi/bin/azure_cpi:34:in `<main>' (00:00:43)

Error 100: #<Bosh::AzureCloud::AzureError: http_put - error: 400 message: {
  "error": {
    "code": "InvalidParameter",
    "target": "vmSize",
    "message": "The value of parameter vmSize is invalid."
  }
}>
```

let's show an error that mentions `instance_type` key must be provided.

### PR DESCRIPTION
**Pull request by AbelHu**
Close #123

### CODE REVIEW

File: src/bosh_azure_cpi/spec/unit/cloud_spec.rb [hunk 1]
```diff
@@ -189,8 +194,28 @@
...
+        expect {
+          cloud.create_vm(
+            agent_id,
+            stemcell_id,
+            {},
+            networks_spec,
+            disk_locality,
+            environment
+          )
+        }.to raise_error("missing required cloud property `instance_type` in resource_pool.")
```
Comment (cppforlife) [inline src/bosh_azure_cpi/spec/unit/cloud_spec.rb]: I would not mention "resource pool". That's a concept in the Director (not the CPI) and we are already moving away from it since we now have VM types.

Also use ' instead of `.
